force-app/main/default/objects/Dataweave_Key_Mapping__mdt/Dataweave_Key_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Dataweave Key Mapping</label>
    <pluralLabel>Dataweave Key Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dataweave_Key_Mapping__mdt/fields/Dataweave_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Dataweave_Mapping__c</fullName>
    <description>Relationship Filed to the Datafield Mapping this record belongs to.</description>
    <label>Dataweave Mapping</label>
    <referenceTo>Dataweave_Mapping__mdt</referenceTo>
    <relationshipLabel>Dataweave Key Mappings</relationshipLabel>
    <relationshipName>Dataweave_Key_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Dataweave_Key_Mapping__mdt/fields/Incoming_Key__c.field-meta.xml
<CustomField>
    <fullName>Incoming_Key__c</fullName>
    <description>This field records the string representation of the key used for this data point in the INCOMING json body</description>
    <label>Incoming Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataweave_Key_Mapping__mdt/fields/Outgoing_Key__c.field-meta.xml
<CustomField>
    <fullName>Outgoing_Key__c</fullName>
    <description>This field holds the string representation of the key you want this data assigned to in the OUTGOING json. For this dataweave script to result in a list of sObjects, this field MUST be the API name of a field on the associated type.</description>
    <label>Outgoing Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dataweave_Mapping__mdt/Dataweave_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Metadata object record sets of Dataweave KeyMappings.</description>
    <label>Dataweave Mapping</label>
    <pluralLabel>Dataweave Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/DWJsonToSObjectsList.cls
/**
 * @description Class provides a re-usable, dynamic and typesafe way to
 * translate an API's JSON response into a list of sObjects.
 */
public with sharing class DWJsonToSObjectsList {
    // incomingJson can be any json string
    private String incomingJson;
    // keyMap is a JSON formatted key:value map where the left side is the name of the
    // key in the incomingJson object, and the right side is the name of the key in
    // the returning json.
    private String keyMap;

    /**
     * @description        full constructor
     * @param incomingJson json string
     * @param keyMap       Map representing JSON key names in the input and output json strings
     */
    public DWJsonToSObjectsList(String incomingJson, String keyMap) {
        this.incomingJson = incomingJson;
        this.keyMap = keyMap;
    }

    /**
     * @description                     Constructor that defines the mapping necessary to
     * translate the incoming json to sObjects from custom metadata
     * @param incomingJson              The incoming JSON to translate
     * @param dataweaveMappingMDTRecord A Dataweave_Mapping__mdt record. This is used to query
     * the Dataweave_Key_Mapping__mdt records.
     */
    public DWJsonToSObjectsList(
        String incomingJson,
        Dataweave_Mapping__mdt dataweaveMappingMDTRecord
    ) {
        this(
            incomingJson,
            fetchMappingFromCustomMetadata(dataweaveMappingMDTRecord)
        );
    }

    /**
     * @description       Given a valid string representation of an sObject
     * this method utilizes class variables of json and keyMap to translate
     * the input json's keys into those specified in the mapping object.
     * @param sObjectType This is the type of List<sObject> to return.
     * @return            `List<sObject>`
     */
    public String translate() {
        Map<String, Object> parameters = new Map<String, Object>();
        parameters.put('mapping', keyMap);
        parameters.put('incomingJson', incomingJson);
        Dataweave.Script script = Dataweave.Script.createScript(
            'json2sObjects'
        );
        DataWeave.Result result = script.execute(parameters);
        return result.getValueAsString();
    }

    /**
     * @description       Method extends the translate method by deserializing the resulting json
     * to a List<sObject>. This method relies on Apex's ability to seamlessly cast from a list of
     * concrete sObjects to a list of generic sObjects. This allows the calling code to cast the
     * resulting list to a List<sObject> to a list of concrete sObject records.
     * @param sObjectType String representation of the concrete sObject type to be returned.
     * @return            `List<sObject>`
     */
    public List<sObject> translateToSObjects(String sObjectType) {
        // construct a Type object reflecting a List of the concrete sObject type specified
        Type dynamicListType = Type.forName('List<' + sObjectType + '>');
        // This line is a doozy, and the bulk of the work happens here.
        // translate is called to get the json string, and then the resulting json is
        // deserialized into a List<sObject> because this list was created
        // with a concrete sObject type, and then cast to a generic sObject list
        // the type system is able to re-cast to a concrete sObject list at the
        // site of the calling code.
        return (List<sObject>) JSON.deserialize(translate(), dynamicListType);
    }

    ///
    /// Helper methods
    ///

    /**
     * @description               Given a Dataweave_Mapping__mdt record, it constructs
     * a JSON string representing the mapping between the incoming json and the sobject requested.
     * @param dataweaveMappingMDT
     * @return                    `String`
     */
    private static String fetchMappingFromCustomMetadata(
        Dataweave_Mapping__mdt dataweaveMappingMDT
    ) {
        List<Dataweave_Key_Mapping__mdt> mappings = [
            SELECT incoming_key__c, outgoing_key__c
            FROM Dataweave_Key_Mapping__mdt
            WHERE Dataweave_Mapping__r.id = :dataweaveMappingMDT.id
            WITH SECURITY_ENFORCED
        ];
        Map<String, String> results = new Map<String, String>();

        // Look, this is a hack. Don't do this in production code.
        // In real code, in the real world, you should dependency inject
        // an object responsible for doing the metadata query below and
        // use the stub API to mock the response.
        // I'm doing this here so as to not introduce a bunch of code
        // just to illustrate how you can DW arbitrary JSON into a list
        // of sObjects, declaratively with custom metadata. Don't hate me.
        // Specifically don't do this whole Test.isRunningTest() thing.
        // START HACKTASTIC CODE.
        if (Test.isRunningTest()) {
            results = DWJsonToSObjectsListTest.getManualMapping();
        } else {
            for (Dataweave_key_mapping__mdt mapping : mappings) {
                results.put(mapping.incoming_key__c, mapping.outgoing_key__c);
            }
        }
        // END HACKTASTIC CODE.

        return JSON.serialize(results);
    }
}